<?php defined('SYSPATH') OR die('No direct access allowed.');

return array
(
    'api_url' => 'http://loginza.ru/api/%method%',
    'version' => '1.0',
    'widget_url' => 'https://loginza.ru/api/widget',
    'widget_id' => '',
    'widget_key' => '',
    'user_model' => 'member',
    'lang' => 'ru',
    'mapping_paths' => array(
        'email' => 'email', 
        'firstname' => 'name.first_name', 
        'lastname' => 'name.last_name', 
        'nickname' => 'nickname',
        'd_birthday' => 'dob',  
    ),
    'providers' => array(
        'yandex.ru' => 'yandex',
        'ya.ru' => 'yandex',
        'vkontakte.ru' => 'vkontakte',
        'vk.com' => 'vkontakte',
        'loginza.ru' => 'loginza',
        'myopenid.com' => 'myopenid',
        'livejournal.com' => 'livejournal',
        'google.ru' => 'google',
        'google.com' => 'google',
        'flickr.com' => 'flickr',
        'mail.ru' => 'mailru',
        'rambler.ru' => 'rambler',
        'webmoney.ru' => 'webmoney',
        'webmoney.com' => 'webmoney',
        'wmkeeper.com' => 'webmoney',
        'wordpress.com' => 'wordpress',
        'blogspot.com' => 'blogger',
        'diary.ru' => 'diary',
        'bestpersons.ru' => 'bestpersons',
        'facebook.com' => 'facebook',
        'twitter.com' => 'twitter',
        'last.fm' => 'lastfm',
        'lastfm.ru' => 'lastfm',
        'verisign' => 'verisign',
        'aol' => 'aol',
        'steam' => 'steam',
        'linkedin' => 'linkedin',
        'odnoklassniki.ru' => 'odnoklassniki',
    ),
);
